server:
  port: 8081
  context-path: /oauthservice
  session:
    cookie:
      name: exampleOauthServiceSessionID
---   
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    data-username: sa
    data-password:
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
     ddl-auto: create-drop
  cloud:
 #   bus:
 #     enabled: false
 #   discovery:
 #     enabled: false
    consul:
      enabled: false
 #     config:
 #       enabled: false

security:
  user:
    name: user
    role:
      USER
    password: password

logging:
 level:
   org.springframework.security: DEBUG
   